[project]
name = "fakellm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "torch>=2.7.1",
    "transformers>=4.53.2",
]
